INSERT INTO BENEFIT(BENEFIT_ID, BENEFIT_NBR, PLAN_NBR, PROC_NBR, YMDTRANS, OPNBR)
VALUES(1, 'BEN001', 'PLAN001', 'PROC001', '2026-01-10', 'OP001');

INSERT INTO BENEFIT(BENEFIT_ID, BENEFIT_NBR, PLAN_NBR, PROC_NBR, YMDTRANS, OPNBR)
VALUES(2, 'BEN002', 'PLAN001', 'PROC002', '2026-01-15', 'OP002');

INSERT INTO BENEFIT(BENEFIT_ID, BENEFIT_NBR, PLAN_NBR, PROC_NBR, YMDTRANS, OPNBR)
VALUES(3, 'BEN003', 'PLAN002', 'PROC003', '2026-02-01', 'OP001');


INSERT INTO COUNTER(CNTR_NAME, TYPE)
VALUES('DEDUCTIBLE', 'DED');

INSERT INTO COUNTER(CNTR_NAME, TYPE)
VALUES('OOP', 'OOP');

INSERT INTO COUNTER(CNTR_NAME, TYPE)
VALUES('LIFETIMEMAX', 'LIFE');
